//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace healthTrackBackend.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class healthtrackdbEntities : DbContext
    {
        public healthtrackdbEntities()
            : base("name=healthtrackdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<caloriesHistory> caloriesHistories { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<caringEnvironmentHistory> caringEnvironmentHistories { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<demeanorHistory> demeanorHistories { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<diseaseCategoryHistory> diseaseCategoryHistories { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<diseaseCategoryType> diseaseCategoryTypes { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<distanceHistory> distanceHistories { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<heartbeatHistory> heartbeatHistories { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<oximetry> oximetries { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<placesHistory> placesHistories { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<recommendationsHistory> recommendationsHistories { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<sleepHistory> sleepHistories { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<specialistByResponsable> specialistByResponsables { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<stepsHistory> stepsHistories { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<treatmentHistory> treatmentHistories { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<user> users { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<userType> userTypes { get; set; }
        [Newtonsoft.Json.JsonIgnore] public virtual DbSet<weightHistory> weightHistories { get; set; }
    }
}
